//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroBlogging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int user_id { get; set; }
        public int post_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int like_count { get; set; }
        public int dislike_count { get; set; }
    }
}
